AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Run testing version of Telegram Bot for cmdict using AWS Lambda.
Resources:
  CmdictTestBot:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      Timeout: 3
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      EphemeralStorage:
        Size: 512
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: BUFFERED
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
      SnapStart:
        ApplyOn: None
      PackageType: Image
    Metadata:
      DockerTag: latest
      DockerContext: ./src
      Dockerfile: Dockerfile
Outputs:
  CmdictTestBotApi:
    Description: Lambda Function URL for testing version of Telegram Bot API.
    Value:
      Fn::GetAtt: CmdictTestBotUrl.FunctionUrl
