name: AWS SAM deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'template.yaml'
      - 'samconfig.toml'
      - '.github/workflows/deploy.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'template.yaml'
      - 'samconfig.toml'
      - '.github/workflows/deploy.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  AWS_REGION: "eu-central-1"

permissions:
  id-token: write
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          role-session-name: ${{ github.run_id }}
          aws-region: ${{ env.AWS_REGION }}
      - run: |
          sam build --use-container
        name: Build
      - run: |
          sam deploy --config-file samconfig.toml \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --resolve-image-repos
        name: Deploy
      - run: |
          curl https://api.telegram.org/bot${{ secrets.CMDICT_BOT }}/setWebhook?url=${{ secrets.FUNCTION_URL }}
          curl https://api.telegram.org/bot${{ secrets.CMDICT_BOT }}/getWebhookInfo
        name: Set WebHook of bot to Function URL
