name: AWS SAM deploy to test bot

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'template.yaml'
      - 'samconfig.toml'
      - '.github/workflows/deploy-test.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: 'eu-central-1'
      - run: |
          sam build --use-container
        name: SAM Build
      - run: sam deploy --config-file samconfig.toml --no-confirm-changeset --no-fail-on-empty-changeset
        name: Deploy to AWS
      # - run: |
      #     curl https://api.telegram.org/bot${{ secrets.CMDICT_TEST_BOT }}/setWebhook?url=${{ secrets.FUNCTION_URL }}
      #     curl https://api.telegram.org/bot${{ secrets.CMDICT_TEST_BOT }}/getWebhookInfo
      #   name: Set WebHook of bot to Function URL
