name: Deploy Bot in Heroku

on:
  workflow_dispatch:
  push:
    branches:
      - main
    ## Deploy only when related files are changed. Learnt from
    ## https://stackoverflow.com/a/63461325/10181743.
    paths:
      - 'main.py'
      - 'requirements.txt'
      - 'Procfile'
      - 'runtime.txt'
      - 'cmdict_bot/**'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: 'eu-central-1'
      - run: sam build --use-container
      - run: sam deploy --config-file samconfig.toml --no-confirm-changeset --no-fail-on-empty-changeset
