name: Deploy Bot in Heroku

on:
  workflow_dispatch:
  push:
    branches:
      - main
    ## Deploy only when related files are changed. Learnt from
    ## https://stackoverflow.com/a/63461325/10181743.
    paths:
      - 'main.py'
      - 'requirements.txt'
      - 'Procfile'
      - 'runtime.txt'
      - 'cmdict_bot/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "cmdict"
          heroku_email: "edxu96@outlook.com"
